{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "warehouse-assistant.serviceAccountName" . }}
  labels:
    {{- include "warehouse-assistant.labels" . | nindent 4 }}
{{- end }}
